[package]
name = "idotmatrix-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.7"
rand = "0.8.5"
tokio = { version = "1.42.0", features = ["rt", "macros", "rt-multi-thread"] }
uuid = "1.11.0"
